### ISSUE TITLE
doesn't work with every nfo file

### ISSUE THREAD

**Issue by paxter** [NewEraCracker/nfo2png#1]
Some charsets/encodings doesn't work with this application. For example the nfos by the group "PsO" doesn't work. You can download a nfo file from here and test it yourself: http://www.xrel.to/movie-nfo/1043909/Alles-steht-Kopf-German-DL-AC3-Dubbed-720p-BluRay-x264-iNTERNAL-PsO.html

Here you see the result how it looks like after converting: http://i.imgur.com/6CYMzve.png

Edit:// Looks like the problem has something to do with unicode. NFO's created in DOS or ASCII are converted correctly, NFO's created in Unicode doesn't.

king regards
Paxter

**Comment by NewEraCracker** [comment]
NFO is a format that uses ASCII encoding for its display in a specific language. My script supports charsets commonly used by English and Russian release creators that adhere to the Scene standards.

If you could supply me the original file (I don't understand German) I could take a look and see if something can be done to correct this problem.

Regards,
NewEraCracker

PS: I could also create a special case that would support non-ASCII encoding based on UTF-8 only, this would work by disabling the `$line = @iconv($encoding, 'UTF-8', $line);` line entirely for such very specific case.

**Comment by paxter** [comment]
No problem. I put two nfos into the zip file for testing: http://www22.zippyshare.com/v/g86e4ca6/file.html
regards
Paxter

**Comment by NewEraCracker** [comment]
You're right about the problem. I'll put this on my TODO list and reply back when it is dealt. I am little busy this days.

**Comment by paxter** [comment]
Thanks for your fast reply! Nice to hear that you'll take a deeper look into the problem later. :)

**Comment by NewEraCracker** [comment]
On the German NFO their encoding is really strange. I could add an option to not perform any encoding corrections when text is already in UTF-8 (with BOM) but the German specific chars will still not work correctly because the codepage for German they've used is not supported by iconv or the font itself.

Please advise if a partial fix would suffice (it would display the ASCII art correctly and all chars on English language but not chars such as 'ä' 'ö' 'ü' and 'ß').

Regards,
NewEraCracker

**Comment by paxter** [comment]
Thanks for your reply. Yes, it would be enough if you fix it without the special chars, because the most important is the ascii and not the text. The most groups doesn't use special chars also. So it would be very nice if you could implement the fix for the special cases if the nfo text is already URF-8.

**Comment by NewEraCracker** [comment]
The problem has now been dealt with.
