### ISSUE TITLE
problem with french nfo file

### ISSUE THREAD

**Issue by paxter** [NewEraCracker/nfo2png#2]
Hi,
I found another nfo which doesn't display correctly. Take look a at this: http://i.imgur.com/16Oqfqe.png

I've uploaded the nfo file here: http://www62.zippyshare.com/v/xiDt5N4w/file.html

**Comment by NewEraCracker** [comment]
I've implemented a workaround for this issue. Should correct the problem. Let me know if any other issue arises.
