### ISSUE TITLE
another nfo with converting problems

### ISSUE THREAD

**Issue by paxter** [NewEraCracker/nfo2png#3]
Check out this nfo file: http://www73.zippyshare.com/v/nuA13hhP/file.html

**Comment by NewEraCracker** [comment]
I wonder who the f**k chooses to use UTF-16 for text encoding... This might be little hackish to implement but will see what can be done.

**Comment by NewEraCracker** [comment]
Let me know if this commit fixes your problem.

**Comment by paxter** [comment]
Thanks for your fast reply. Unfortunately the fix doesn't work for me: http://i.imgur.com/D4H2FPP.png

**Comment by NewEraCracker** [comment]
May I know which PHP version are you using and respective OS ?

**Comment by paxter** [comment]
PHP Version 5.6.14;Windows 7

**Comment by NewEraCracker** [comment]
My bet is that mbstring version shipped with PHP 5.6 may have certain incompatibilities. I test this script with PHP 5.3 and it works. I'll see if I can "hack" something to make it work in every version.

**Comment by paxter** [comment]
That would be nice. I will test it with another php version.

**Comment by NewEraCracker** [comment]
This commit **might** fix your problem. Let me know if it works.

**Comment by paxter** [comment]
Thanks again for the fix. It's working now without problems. :)
