### ISSUE TITLE
Problem with hostdir

### ISSUE THREAD

**Issue by wgth26414** [NewEraCracker/nfo2png#5]
hey i dont know if its a bug or its me who is doing something wrong.. 

but i have setup the server and the $hotdir
my hostdir looks like this 
$hostDir = '/nfo/';

and i get this message anyway "It was not possible to write image into filesystem."
can u maybe help me

**Comment by paxter** [comment]
Does the folder `/nfo/` exist on your filesystem? Maybe you wanted `./nfo/`?

**Comment by wgth26414** [comment]
yes it does.. its in the folder `/var/www/html/nfo2png/nfo`

**Comment by NewEraCracker** [comment]
change the permissions to allow writing in the directory and/or chown it to the same user as the php/webserver process...

**Comment by paxter** [comment]
> yes it does.. its in the folder `/var/www/html/nfo2png/nfo`

Nope. `/var/www/html/nfo2png/nfo` is not the same as `/nfo/`. Use the correct path and consider NewEraCrackers hints.

**Comment by wgth26414** [comment]
Thanks for the help forgot to give chown..
